trigger:
- master

variables:
- name: BuildConfiguration
  value: Development

- name: PackageID
  value: MyExampleProj.csproj

- name: ConnectedSvcName
  value: danefalvo2.testoctopus.com

- name: OctoSpace
  value: Default

- name: ConnectedSvcName
  value: danefalvo2.testoctopus.com

- name: OctoProject
  value: Pushed from Azure

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Get-ChildItem -Path ''D:\a\1\s'' -recurse'
    errorActionPreference: 'silentlyContinue'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'gci -rec -directory | select-object fullname'

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: 'runtime'
    version: '3.1.x'


- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(PackageID)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(PackageID)'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: false

- task: OctopusPack@4
  inputs:
    PackageId: '$(PackageID)'
    PackageFormat: 'NuPkg'
    PackageVersion: '$(Build.BuildNumber)'
    SourcePath: '$(build.artifactstagingdirectory)'
    OutputPath: '$(build.stagingdirectory)'
    NuGetTitle: '$(PackageID)'
    NuGetDescription: 'Development of $(PackageID)'
    NuGetReleaseNotes: '$(Build.SourceVersionMessage)'
    NuGetReleaseNotesFile: 'NotesForComment.md'
    Overwrite: true
    ListFiles: true
    AdditionalArguments: '--title=new title'

        
- task: OctopusMetadata@4
  inputs:
    OctoConnectedServiceName: '$(ConnectedSvcName)'
    Space: '$(OctoSpace)'
    PackageId: '$(PackageID)'
    PackageVersion: '$(Build.BuildNumber)'
    Replace: 'false'


- task: OctopusPush@4
  inputs:
    OctoConnectedServiceName: '$(ConnectedSvcName)'
    Space: '$(OctoSpace)'
    Package: '$(build.stagingdirectory)/*.nupkg'
    Replace: 'true'



- task: OctopusCreateRelease@4
  inputs:
    OctoConnectedServiceName: '$(ConnectedSvcName)'
    Space: '$(OctoSpace)'
    ProjectName: '$(OctoProject)'
    ReleaseNumber: '$(Build.BuildNumber)'
