trigger:
- master

variables:
- name: BuildConfiguration
  value: Development 

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Get-ChildItem -Path ''D:\a\1\s'' -recurse'
    errorActionPreference: 'silentlyContinue'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'gci -rec -directory | select-object fullname'
    


- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: 'runtime'
    version: '3.1.x'


- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'MyExampleProj.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'MyExampleProj.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: false

- task: OctopusPack@4
  inputs:
    PackageId: 'MyExampleProj.csproj'
    PackageFormat: 'NuPkg'
    PackageVersion: '$(Build.BuildNumber)'
    SourcePath: '$(build.artifactstagingdirectory)'
    OutputPath: '$(build.stagingdirectory)'
    NuGetTitle: 'MyDotNetCoreAppGITExample This will be the title of the package that Im making really really long'
    NuGetDescription: 'Development of MyDotNetCoreAppGit The title of this package is MyDotNetCoreAppGITExample'
    NuGetReleaseNotes: '$(Build.SourceVersionMessage)'
    NuGetReleaseNotesFile: 'NotesForComment.md'
    Overwrite: true
    ListFiles: true
    AdditionalArguments: '--title=new title'

        
- task: OctopusMetadata@4
  inputs:
    OctoConnectedServiceName: 'danefalvo2.testoctopus.com'
    Space: 'Default'
    PackageId: '$(ImageName)'
    PackageVersion: '$(Build.BuildNumber)'
    Replace: 'false'


- task: OctopusPush@4
  inputs:
    OctoConnectedServiceName: 'danefalvo2.testoctopus.com'
    Space: 'Default'
    Package: '$(build.stagingdirectory)/*.nupkg'
    Replace: 'true'



- task: OctopusCreateRelease@4
  inputs:
    OctoConnectedServiceName: 'danefalvo2.testoctopus.com'
    Space: 'Default'
    ProjectName: 'Pushed-from-azure'
    ReleaseNumber: '$(Build.BuildNumber)'
